# Generated by Django 3.2.16 on 2023-01-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_format', models.IntegerField(choices=[(1, 'Text'), (2, 'Code'), (3, 'Code Editor')])),
                ('paragraph_number', models.IntegerField(null=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
        ),
    ]
