# Generated by Django 3.2.16 on 2023-01-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_textblock_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textblocks', to='core.topic'),
        ),
    ]
