# Generated by Django 3.2.17 on 2023-02-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_textblocks', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_textblocks', to='core.topic'),
        ),
    ]
