# Generated by Django 3.2.17 on 2023-02-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_started_code_filename_exercise_starter_code_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='expected_outcome_filename',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='starter_code_filename',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='expected_outcome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='starter_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
