# Generated by Django 3.2.17 on 2023-02-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230210_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='expected_outcome',
            new_name='expected_output',
        ),
    ]
