# Generated by Django 3.2.17 on 2023-02-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_expected_outcome_exercise_expected_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textblock',
            name='topic',
        ),
        migrations.AddField(
            model_name='textblock',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_textblocks', to='core.exercise'),
        ),
    ]
