# Generated by Django 3.2.18 on 2023-02-21 09:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230220_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.lesson_image_file_path),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='text_format',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Code'), (3, 'Code Editor'), (4, 'Paragraph'), (5, 'Heading 1'), (6, 'Heading 2'), (7, 'Heading 3'), (8, 'Image')]),
        ),
    ]
